### ISSUE TITLE
main image for problems

### ISSUE THREAD

**Issue by robjuz** [robjuz/KoVicky#10]

**Comment by makakken** [comment]
works good for now ;)
forgot to update my migrations.
and i had to install plugin: **proffer** manually...

**Comment by makakken** [comment]
if there is time, we should talk about fixing the css :)
![bildschirmfoto vom 2016-05-07 20 54 27](https://cloud.githubusercontent.com/assets/10586572/15093948/8376bafe-1496-11e6-8440-1edc3d0fc21e.png)
